version: '3.8'

services:
  dwh:
    container_name: dwh
    image: postgres:11-alpine
    restart: always
    env_file:
      - etl/.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables (initial step)
      - ./etl/sql/init_db.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - app-network
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  etl_test:
    container_name: etl_test
    build:
      context: ./etl
      dockerfile: DockerfileTests
    volumes:
      - ./etl:/etl
    depends_on:
      dwh:
        condition: service_healthy
    networks:
      - app-network

  etl:
    container_name: etl
    build:
      context: ./etl
      dockerfile: Dockerfile
    depends_on:
      - etl_test
    networks:
      - app-network
    configs:
      - etl_conf

volumes:
  postgres_data:

networks:
  app-network:

configs:
  etl_conf:
    file: ./etl/configs/etl_conf.json
